<?php

namespace Heartsentwined\Vcard\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FamilyName
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyName extends EntityRepository
{
}
