<?php

namespace Heartsentwined\Vcard\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GivenName
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GivenName extends EntityRepository
{
}
