<?php

namespace Heartsentwined\Vcard\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Im
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Im extends EntityRepository
{
}
