<?php

namespace Heartsentwined\Vcard\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImProtocol
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImProtocol extends EntityRepository
{
    const AIM       = 'aim';
    const GADUGADU  = 'gadugadu';
    const GROUPWISE = 'groupwise';
    const ICQ       = 'icq';
    const JABBER    = 'jabber';
    const MSN       = 'msn';
    const SKYPE     = 'skype';
    const TWITTER   = 'twitter';
    const YAHOO     = 'yahoo';
}
