<?php

namespace Heartsentwined\Vcard\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Kind
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Kind extends EntityRepository
{
    const DEF           = 'individual';

    const INDIVIDUAL    = 'individual';
    const GROUP         = 'group';
    const ORG           = 'org';
    const ORGANIZATION  = 'org'; // alias
    const LOCATION      = 'location';
}
