<?php

namespace Heartsentwined\Vcard\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Member
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Member extends EntityRepository
{
}
