<?php

namespace Yalesov\Vcard\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdditionalName
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionalName extends EntityRepository
{
}
