<?php

namespace Yalesov\Vcard\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GenderValue
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenderValue extends EntityRepository
{
  const M         = 'M';
    const MALE      = 'M';
  const F         = 'F';
    const FEMALE    = 'F';
  const O         = 'O';
    const OTHER     = 'O';
  const N         = 'N';
    const NONE      = 'N';
    const NA      = 'N';
    const NOTAPPLICABLE = 'N';
  const U         = 'U';
    const UNKNOWN     = 'U';
}
