<?php

namespace Yalesov\Vcard\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Meta
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Meta extends EntityRepository
{
    const INSTALLED = 'installed';
}
