<?php

namespace Yalesov\Vcard\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NicknameValue
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NicknameValue extends EntityRepository
{
}
