<?php

namespace Yalesov\Vcard\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneType
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneType extends EntityRepository
{
  const DEF     = 'voice';

  const TEXT    = 'text';
  const VOICE   = 'voice';
  const FAX     = 'fax';
  const CELL    = 'cell';
  const VIDEO   = 'video';
  const PAGER   = 'pager';
  const TEXTPHONE = 'textphone';
}
