<?php

namespace Yalesov\Vcard\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RelationType
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationType extends EntityRepository
{
    const CONTACT       = 'contact';
    const ACQUAINTANCE  = 'acquaintance';
    const FRIEND        = 'friend';
    const MET           = 'met';
    const COWORKER      = 'co-worker';
    const COLLEAGUE     = 'colleague';
    const CORESIDENT    = 'co-resident';
    const NEIGHBOR      = 'neighbor';
    const NEIGHBOUR     = 'neighbor';   // alias
    const CHILD         = 'child';
    const PARENT        = 'parent';
    const SIBLING       = 'sibling';
    const SPOUSE        = 'spouse';
    const KIN           = 'kin';
    const MUSE          = 'muse';
    const CRUSH         = 'crush';
    const DATE          = 'date';
    const SWEETHEART    = 'sweetheart';
    const ME            = 'me';
    const AGENT         = 'agent';
    const EMERGENCY     = 'emergency';
}
