<?php

namespace Yalesov\Vcard\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Suffix
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Suffix extends EntityRepository
{
}
